### ISSUE TITLE
Move test/ suite into the Python package as a subpackage

### ISSUE THREAD

**Issue by duncanmmacleod** [cwinpy/cwinpy#5]
It would be great to see the `test/` directory moved inside the `cwinpy/` directory so that it's installed with the package as a `cwinpy.test{s}` subpackage. This would enable in-situ testing of `cwinpy` after installation (when the tarball isn't available).

**Comment by mattpitkin** [comment]
This has been done in https://github.com/cwinpy/cwinpy/commit/b44c82e1657145878d5a5c221ef95f954fa668a8, although I've not made a new release with these changes yet.
